# Generated by Django 5.1.1 on 2025-11-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
    ]
