# Generated by Django 5.1.1 on 2025-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='photo',
            field=models.ImageField(default='photos/default-profile.png', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(default='photos/default-profile.png', upload_to='photos/'),
        ),
    ]
