# Generated by Django 5.1.1 on 2025-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_serviceproviderprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
