# Generated by Django 5.1.1 on 2025-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_review_user_review_customer_review_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='photos/tutoring.jpeg', upload_to='photos/'),
        ),
    ]
