# Generated by Django 5.1.1 on 2025-11-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_booking_note_alter_review_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='photos/default-service.jpg', upload_to='photos/'),
        ),
    ]
