# Generated by Django 5.1.1 on 2025-11-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='photos/default-service.jpeg', upload_to='photos/'),
        ),
    ]
