# Generated by Django 5.1.1 on 2025-11-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_recentserviceview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='ServiceProviderProfile',
        ),
    ]
